unique_name: country_groups_row_security
object_type: row_security
label: country_groups_row_security
dataset: country_security_map_groups
filter_key_column: country
id_type: group
ids_column: group_name
scope: all
secure_totals: false
use_filter_key: true
