unique_name: productline_groups_row_security
object_type: row_security
label: productline_groups_row_security
dataset: PRODUCTLINE_SECURITY_MAP_GROUPS
filter_key_column: PRODUCTLINE
id_type: group
ids_column: GROUP_NAME
scope: all
secure_totals: false
use_filter_key: true
