unique_name: productline_users_row_security
object_type: row_security
label: productline_users_row_security
dataset: productline_security_map_users
filter_key_column: productline
id_type: user
ids_column: username
scope: all
secure_totals: false
use_filter_key: true
