unique_name: productline_security_map_users
object_type: dataset
label: productline_security_map_users
columns:
  - name: productline
    data_type: string
  - name: username
    data_type: string
connection_id: Connection - Internet Sales
table: productline_security_map_users
