unique_name: PRODUCTLINE_SECURITY_MAP_USERS
object_type: dataset
label: PRODUCTLINE_SECURITY_MAP_USERS
columns:
  - name: PRODUCTLINE
    data_type: string
  - name: USERNAME
    data_type: string
connection_id: Connection - Internet Sales
table: PRODUCTLINE_SECURITY_MAP_USERS
